services:
  backend:
    build:
      context: ../starwarsbackend
      dockerfile: Dockerfile
    container_name: starwars-java-backend
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starwars-angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

